travis:
  secure:
    BINSTAR_TOKEN: hdtDXHIfogN152zDlq2g97DVFTDLRTcDzHXeIXy6bWxQGU4iLkAYWYQTjj/yHqowhlyl4zLJaf+TqOyZYUpYvpNQ7sdEnS1sG0XbSTIFjAJseCFwSNGjLJRMO1x3FPmn+XqnIRQHwmVuOdV6vSXhEsnHoRkhICds23z3VDbNcv/EPaPogxAHfM/MQNtvCAPslzYP/fK71pLM8sN2Kz8W4/FEeqS+1+uPqCA/Z1WfhwzQw7LZT6Od4ufFCqRAr2ND4D5YcZdMwqFlBtIcl2iJWu5W16iQcQOa7hKgtkR0bcIwR0HYE1/Y2ij96IYIVhUsDAYUiQbFd2euKwEKOjcYh5tZz75FglffEXAaTOfk8/SpLu5ilv2bTT5BhKO81BWa3V5uZsyx5PMFcfYqy0gb1nxlI9rth+nQaIJNj5oW7xHe9F3weKDF88RfZSHZdpTAAy7wdEnLYc3+r0UpFNRG38Epf8rKl4OoP8TyrNCxI2KdNbqAM+UbCWWc3pwxFw8DjIeRbX5q1bby+UvMA1l1IK/QOBykr8Rwymtze+7FCH1vySR9m75Gkkz89Mpmga0xUmoZ08nvcPjT/qSPM6EURnF5FVU04Yn7+z9YiZm8wkAb7HyNoht7fYhRyPefubCAAjzzPXD4GPeHvtNzurdYAsLG665RtPov/m3XvuU26dQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
conda_forge_output_validation: false
